version: "3.8"
services:

  # assess policy compliance
  compliance:
    build: "engine/"
    ports:
      - "8060:8060"
    entrypoint: "sleep infinity"
    volumes:
      - ./:/core/
    depends_on:
      - influxdb
  
  # display policy compliance using Plotly
  visualization:
    build: "visualization/"
    ports:
      - "8000:8000"
    entrypoint: "sleep infinity"
    depends_on:
      - influxdb
  
  # display policy compliance using Chronograf
  chronograf:
    image: chronograf
    ports:
      - "8888:8888"
    depends_on:
      - influxdb
    volumes:
      - ./chronograf:/var/lib/chronograf

  # store policy compliance
  influxdb:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    environment:
      - influxdb_db=routing_compliance
      - influxdb_user=root
      - influxdb_user_password=root

  # Telemetry input
  telegraf:
    build: "telegraf"
    ports:
      - "35005:35005"
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "telegraf"
      GRPC_PORT: "35005"
    depends_on:
      - influxdb