version: "3.8"
services:

  # assess policy compliance
  compliance:
    image: "python:3.8"
    ports:
      - "8001:8001"
    entrypoint: "sleep infinity"
  
  # display policy compliance
  visualization:
    build: "visualization/"
    ports:
      - "8000:8000"
    entrypoint: "sleep infinity"

  # store policy compliance
  influxdb:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    environment:
      - influxdb_db=routing_compliance
      - influxdb_user=root
      - influxdb_user_password=root

  # Telemetry input
  telegraf:
    build: "telegraf"
    ports:
      - "35005:35005"
    environment:
      HOST_NAME: "telegraf"
      INFLUXDB_HOST: "influxdb"
      INFLUXDB_PORT: "8086"
      DATABASE: "telegraf"
      GRPC_PORT: "35005"