version: "3.8"
services:

  # assess policy compliance
  compliance:
    build: "engine/"
    ports:
      - "8060:8060"
    entrypoint: "sleep infinity"
    volumes:
      - ./:/core/
  
  # display policy compliance
  visualization:
    build: "visualization/"
    ports:
      - "8000:8000"
    entrypoint: "sleep infinity"

  # store policy compliance
  influxdb:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    environment:
      - influxdb_db=routing_compliance
      - influxdb_user=root
      - influxdb_user_password=root
