version: "3.8"
services:
  web:
    image: "python:3.8"
    ports:
      - "8000:8000"
    entrypoint: "sleep infinity"
  influxdb:
    image: "influxdb:alpine"
    ports:
      - "8086:8086"
    environment:
      - influxdb_db=routing_compliance
      - influxdb_user=root
      - influxdb_user_password=root
  compliance:
    image: "python:3.8"
    ports:
      - "8001:8001"
    entrypoint: "sleep infinity"